# Generated by Django 5.0.1 on 2024-01-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_listing_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="active",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="winner",
        ),
    ]
